language: python

env:
  global:
    - CC_TEST_REPORTER_ID=3b92efbe2bff1d91058380e57b3eb8d12a9d5d40ae59eb7002b53e9c6b9d41dd

python:
  - "3.5"
  - "3.6"

install:
  - pip install pipenv
  - pipenv install -d

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - pytest --cov-report= --cov=mpl_axes_aligner

after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
